@startuml
namespace accounting {
    class AccountBalance << (S,Aquamarine) >> {
        + CompanyName string
        + AccountingCode string
        + DebitAmount int
        + CreditAmount int

    }
    class AccountingCode << (S,Aquamarine) >> {
    }
    class AccountingItem << (S,Aquamarine) >> {
        + OrgClass string
        + OrgNumber string
        + OrgName string

    }
    class AccountingNode << (S,Aquamarine) >> {
        + DebitAmount int
        + CreditAmount int
        + Code string
        + Children []*AccountingNode

    }
    class Voucher << (S,Aquamarine) >> {
        + CompanyId int
        + VoucherDate string
        + VoucherEntries []VoucherEntry

    }
    class VoucherEntry << (S,Aquamarine) >> {
        + Remark string
        + AccountCode string
        + AccountingItems []AccountingItem
        + DebitAmount int
        + CreditAmount int

    }
}


@enduml
